// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Gps_speedometer

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x3B3939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Screen1, &ui_img_speedfg_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT );

ui_RootPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_RootPanel, lv_pct(50));
lv_obj_set_height( ui_RootPanel, lv_pct(100));
lv_obj_set_x( ui_RootPanel, 10 );
lv_obj_set_y( ui_RootPanel, -9 );
lv_obj_set_align( ui_RootPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RootPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RootPanel, lv_color_hex(0x020302), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RootPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RootPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RootPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopPanel = lv_obj_create(ui_RootPanel);
lv_obj_set_width( ui_TopPanel, 148);
lv_obj_set_height( ui_TopPanel, 50);
lv_obj_set_x( ui_TopPanel, -13 );
lv_obj_set_y( ui_TopPanel, -203 );
lv_obj_set_align( ui_TopPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x3A3641), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TopPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_TopPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TopPanel, lv_color_hex(0x0FA0F2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TopPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TopPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_TopPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_TopPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_TopPanel, lv_color_hex(0xF7F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TopPanel, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title = lv_label_create(ui_TopPanel);
lv_obj_set_width( ui_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title,"Speedometer");
lv_obj_set_style_text_color(ui_Title, lv_color_hex(0x1490E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Title, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedPanel = lv_obj_create(ui_Screen1);
lv_obj_set_height( ui_SpeedPanel, 140);
lv_obj_set_width( ui_SpeedPanel, lv_pct(50));
lv_obj_set_x( ui_SpeedPanel, 9 );
lv_obj_set_y( ui_SpeedPanel, -103 );
lv_obj_set_align( ui_SpeedPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SpeedPanel, lv_color_hex(0x181616), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SpeedPanel, lv_color_hex(0x080808), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SpeedPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedBG = lv_img_create(ui_SpeedPanel);
lv_img_set_src(ui_SpeedBG, &ui_img_speedbg_png);
lv_obj_set_width( ui_SpeedBG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedBG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedBG, 2 );
lv_obj_set_y( ui_SpeedBG, 2 );
lv_obj_set_align( ui_SpeedBG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpeedBG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SpeedBG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SpeedSlider = lv_slider_create(ui_SpeedBG);
lv_slider_set_range(ui_SpeedSlider, 0,200);
lv_slider_set_value( ui_SpeedSlider, 120, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SpeedSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SpeedSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SpeedSlider, 320);
lv_obj_set_height( ui_SpeedSlider, 140);
lv_obj_set_align( ui_SpeedSlider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SpeedSlider, &ui_img_speedfg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SpeedMinLabel = lv_label_create(ui_SpeedPanel);
lv_obj_set_width( ui_SpeedMinLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedMinLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedMinLabel, -144 );
lv_obj_set_y( ui_SpeedMinLabel, 44 );
lv_obj_set_align( ui_SpeedMinLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedMinLabel,"0");
lv_obj_set_style_text_color(ui_SpeedMinLabel, lv_color_hex(0xF8F0F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedMinLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedMinLabel, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedMaxLabel = lv_label_create(ui_SpeedPanel);
lv_obj_set_width( ui_SpeedMaxLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedMaxLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedMaxLabel, 152 );
lv_obj_set_y( ui_SpeedMaxLabel, -40 );
lv_obj_set_align( ui_SpeedMaxLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedMaxLabel,"200");
lv_obj_set_style_text_color(ui_SpeedMaxLabel, lv_color_hex(0xF8F0F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedMaxLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedMaxLabel, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompassPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_CompassPanel, lv_pct(50));
lv_obj_set_height( ui_CompassPanel, lv_pct(55));
lv_obj_set_x( ui_CompassPanel, 6 );
lv_obj_set_y( ui_CompassPanel, 99 );
lv_obj_set_align( ui_CompassPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CompassPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CompassPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CompassPanel, lv_color_hex(0x0C0B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CompassPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_CompassPanel, lv_color_hex(0x060606), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_CompassPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CompassPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CompassPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompassImg = lv_img_create(ui_CompassPanel);
lv_img_set_src(ui_CompassImg, &ui_img_compass_png);
lv_obj_set_width( ui_CompassImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CompassImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CompassImg, 0 );
lv_obj_set_y( ui_CompassImg, 9 );
lv_obj_set_align( ui_CompassImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CompassImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CompassImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_CompassImg,1);
lv_img_set_zoom(ui_CompassImg,250);

ui_CompassLabel = lv_label_create(ui_CompassPanel);
lv_obj_set_width( ui_CompassLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CompassLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CompassLabel, -1 );
lv_obj_set_y( ui_CompassLabel, 3 );
lv_obj_set_align( ui_CompassLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CompassLabel,"360");
lv_obj_set_style_text_color(ui_CompassLabel, lv_color_hex(0x15A8E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CompassLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CompassLabel, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedTextPanel = lv_obj_create(ui_Screen1);
lv_obj_set_height( ui_SpeedTextPanel, 40);
lv_obj_set_width( ui_SpeedTextPanel, lv_pct(50));
lv_obj_set_x( ui_SpeedTextPanel, 11 );
lv_obj_set_y( ui_SpeedTextPanel, -27 );
lv_obj_set_align( ui_SpeedTextPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpeedTextPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SpeedTextPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedTextPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SpeedTextPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedUnitLabel = lv_label_create(ui_SpeedTextPanel);
lv_obj_set_width( ui_SpeedUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedUnitLabel, 8 );
lv_obj_set_y( ui_SpeedUnitLabel, 19 );
lv_obj_set_align( ui_SpeedUnitLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_SpeedUnitLabel,"mph");
lv_obj_set_style_text_color(ui_SpeedUnitLabel, lv_color_hex(0xF7F3F3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedUnitLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedUnitLabel, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedLabelBack = lv_label_create(ui_SpeedTextPanel);
lv_obj_set_width( ui_SpeedLabelBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedLabelBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedLabelBack, -45 );
lv_obj_set_y( ui_SpeedLabelBack, 18 );
lv_obj_set_align( ui_SpeedLabelBack, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_SpeedLabelBack,"000");
lv_obj_set_style_text_color(ui_SpeedLabelBack, lv_color_hex(0xF7F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedLabelBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedLabelBack, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SpeedSlider, ui_event_SpeedSlider, LV_EVENT_ALL, NULL);

}
