// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Gps_speedometer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_RootPanel;
lv_obj_t *ui_TopPanel;
lv_obj_t *ui_Title;
lv_obj_t *ui_SpeedPanel;
lv_obj_t *ui_SpeedBG;
void ui_event_SpeedSlider( lv_event_t * e);
lv_obj_t *ui_SpeedSlider;
lv_obj_t *ui_SpeedMinLabel;
lv_obj_t *ui_SpeedMaxLabel;
lv_obj_t *ui_CompassPanel;
lv_obj_t *ui_CompassImg;
lv_obj_t *ui_CompassLabel;
lv_obj_t *ui_SpeedTextPanel;
lv_obj_t *ui_SpeedUnitLabel;
lv_obj_t *ui_SpeedLabelBack;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SpeedSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_slider_increment( ui_SpeedSlider, 1, LV_ANIM_ON);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
