// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Gps_speedometer

#ifndef _GPS_SPEEDOMETER_UI_H
#define _GPS_SPEEDOMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_RootPanel;
extern lv_obj_t *ui_TopPanel;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_SpeedPanel;
extern lv_obj_t *ui_SpeedBG;
void ui_event_SpeedSlider( lv_event_t * e);
extern lv_obj_t *ui_SpeedSlider;
extern lv_obj_t *ui_SpeedMinLabel;
extern lv_obj_t *ui_SpeedMaxLabel;
extern lv_obj_t *ui_CompassPanel;
extern lv_obj_t *ui_CompassImg;
extern lv_obj_t *ui_CompassLabel;
extern lv_obj_t *ui_SpeedTextPanel;
extern lv_obj_t *ui_SpeedUnitLabel;
extern lv_obj_t *ui_SpeedLabelBack;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_speedfg_png);   // assets/speedFG.png
LV_IMG_DECLARE( ui_img_speedbg_png);   // assets/speedBG.png
LV_IMG_DECLARE( ui_img_compass_png);   // assets/compass.png

LV_FONT_DECLARE( ui_font_Display16);
LV_FONT_DECLARE( ui_font_Display24);
LV_FONT_DECLARE( ui_font_Display90);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
